import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Layout  from '../components/Layout'

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Next generation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </React.Fragment>
  )
}

export default Home
